language: node_js
sudo: false
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"
env:
  - KARMA_VERSION=5.2.3
addons:
  chrome: stable
before_install:
  - npm install --save-dev karma@"$KARMA_VERSION"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - export KARMA_BROWSER=Firefox,Chrome_NoSandbox
